### ISSUE TITLE
Frame Delay per frame?

### ISSUE THREAD

**Issue by grene78** [mrousavy/AnimatedGif#1]
Any plans to add this?

Looks like it might be a pretty easy tweak.

**Comment by mrousavy** [comment]
Done in #2.
Please check if it works out for you.

Sorry for the long time no response!

**Comment by grene78** [comment]
I actually added it myself shortly after mentioning it but I figured others might need it as well.  Thanks for this code, it's great!  I was hitting my head against the wall with the MS gif encoder, and your code with the quantizer works beautifully.
