### ISSUE TITLE
AddFrame delay parameter missing

### ISSUE THREAD

**Issue by jvitoroc** [mrousavy/AnimatedGif#3]
There is a delay parameter in the AddFrame method: [AnimatedGifCreator.cs#L55](https://github.com/mrousavy/AnimatedGif/blob/master/AnimatedGif/AnimatedGifCreator.cs#L55) but I can't access it

![image](https://user-images.githubusercontent.com/25753747/40999043-1465ec3e-68e0-11e8-8867-3ad49521d8a7.png)

Sorry for my EN

**Comment by mrousavy** [comment]
Whoops, my bad I forgot to update the Package on **NuGet**!
Just submitted it, update it on your Project and it should work.

**Comment by jvitoroc** [comment]
I compiled myself after posting this issue. Thanks by the way.
